#ifndef PRINT_DIALOG_ENUMS_H
#define PRINT_DIALOG_ENUMS_H

#define MAINTENANCE_TYPE_NONE 0
#define MAINTENANCE_TYPE_CLEANING 1
#define MAINTENANCE_TYPE_NOZZLE_CHECK 2

#define PRINT_DIALOG_RES_NO 0
#define PRINT_DIALOG_RES_YES 1
#define PRINT_DIALOG_RES_CLEANING 2

#define PRINT_DIALOG_OK 0
#define PRINT_DIALOG_QUERY_CLEAN 1
#define PRINT_DIALOG_QUERY 2

#endif